include:
  - path: docker-compose.yml

services:
  ovms-vlm:
    devices: !reset
      - /dev/dxg:/dev/dxg
    volumes:
      - /usr/lib/wsl/lib:/usr/lib/wsl/lib:ro
      - /usr/lib/wsl/drivers:/usr/lib/wsl/drivers:ro
      - /etc/OpenCL:/etc/OpenCL:ro
    environment:
      LD_LIBRARY_PATH: /usr/lib/wsl/lib:/ovms/lib

  lp-vlm-workload-handler:
    devices: !reset
      - /dev/dxg:/dev/dxg
    volumes:
      - /usr/lib/wsl/lib:/usr/lib/wsl/lib:ro
      - /usr/lib/wsl/drivers:/usr/lib/wsl/drivers:ro
      - /etc/OpenCL:/etc/OpenCL:ro
    environment:
      LD_LIBRARY_PATH: /usr/lib/wsl/lib:/opt/intel/openvino/runtime/lib/intel64

  lp-pipeline-runner:
    devices:
      - /dev/dxg:/dev/dxg
    volumes:
      - /usr/lib/wsl/lib:/usr/lib/wsl/lib:ro
      - /usr/lib/wsl/drivers:/usr/lib/wsl/drivers:ro
      - /etc/OpenCL:/etc/OpenCL:ro
    environment:
      VIDEO_SINK: ximagesink